#spring.application.name=UberBookingService
#server.port=7777
#spring.datasource.url=jdbc:mysql://localhost:3306/Uber_DB_Local
#spring.datasource.username=root
#spring.datasource.password=Root@123
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: UberBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/Uber_DB_Local
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # --- Kafka Configuration ---
  Kafka:
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

